//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payment_posting.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class paymentEntities : DbContext
    {
        public paymentEntities()
            : base("name=paymentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<payment_center> payment_center { get; set; }
    
        public virtual ObjectResult<parse_data_format_Result> parse_data_format(string pc_id)
        {
            var pc_idParameter = pc_id != null ?
                new ObjectParameter("pc_id", pc_id) :
                new ObjectParameter("pc_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<parse_data_format_Result>("parse_data_format", pc_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ClearTreasurerReceipts(Nullable<byte> nReceiptType)
        {
            var nReceiptTypeParameter = nReceiptType.HasValue ?
                new ObjectParameter("nReceiptType", nReceiptType) :
                new ObjectParameter("nReceiptType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ClearTreasurerReceipts", nReceiptTypeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CollPostPaymentMain1(string sORNo, string sAccountID, Nullable<decimal> nORAmount, Nullable<System.DateTime> dPaymentDate, Nullable<bool> bReConnect)
        {
            var sORNoParameter = sORNo != null ?
                new ObjectParameter("sORNo", sORNo) :
                new ObjectParameter("sORNo", typeof(string));
    
            var sAccountIDParameter = sAccountID != null ?
                new ObjectParameter("sAccountID", sAccountID) :
                new ObjectParameter("sAccountID", typeof(string));
    
            var nORAmountParameter = nORAmount.HasValue ?
                new ObjectParameter("nORAmount", nORAmount) :
                new ObjectParameter("nORAmount", typeof(decimal));
    
            var dPaymentDateParameter = dPaymentDate.HasValue ?
                new ObjectParameter("dPaymentDate", dPaymentDate) :
                new ObjectParameter("dPaymentDate", typeof(System.DateTime));
    
            var bReConnectParameter = bReConnect.HasValue ?
                new ObjectParameter("bReConnect", bReConnect) :
                new ObjectParameter("bReConnect", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CollPostPaymentMain1", sORNoParameter, sAccountIDParameter, nORAmountParameter, dPaymentDateParameter, bReConnectParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GenerateTreasurerReceipt1(Nullable<System.DateTime> dFromPaymentDate, Nullable<System.DateTime> dToPaymentDate, Nullable<System.DateTime> dTreasurerReceiptDate, Nullable<byte> nFromTerminalID, Nullable<byte> nToTerminalID, Nullable<byte> nReceiptType)
        {
            var dFromPaymentDateParameter = dFromPaymentDate.HasValue ?
                new ObjectParameter("dFromPaymentDate", dFromPaymentDate) :
                new ObjectParameter("dFromPaymentDate", typeof(System.DateTime));
    
            var dToPaymentDateParameter = dToPaymentDate.HasValue ?
                new ObjectParameter("dToPaymentDate", dToPaymentDate) :
                new ObjectParameter("dToPaymentDate", typeof(System.DateTime));
    
            var dTreasurerReceiptDateParameter = dTreasurerReceiptDate.HasValue ?
                new ObjectParameter("dTreasurerReceiptDate", dTreasurerReceiptDate) :
                new ObjectParameter("dTreasurerReceiptDate", typeof(System.DateTime));
    
            var nFromTerminalIDParameter = nFromTerminalID.HasValue ?
                new ObjectParameter("nFromTerminalID", nFromTerminalID) :
                new ObjectParameter("nFromTerminalID", typeof(byte));
    
            var nToTerminalIDParameter = nToTerminalID.HasValue ?
                new ObjectParameter("nToTerminalID", nToTerminalID) :
                new ObjectParameter("nToTerminalID", typeof(byte));
    
            var nReceiptTypeParameter = nReceiptType.HasValue ?
                new ObjectParameter("nReceiptType", nReceiptType) :
                new ObjectParameter("nReceiptType", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GenerateTreasurerReceipt1", dFromPaymentDateParameter, dToPaymentDateParameter, dTreasurerReceiptDateParameter, nFromTerminalIDParameter, nToTerminalIDParameter, nReceiptTypeParameter);
        }
    
        public virtual ObjectResult<getMOInProgress_Result> getMOInProgress()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMOInProgress_Result>("getMOInProgress");
        }
    
        public virtual ObjectResult<Nullable<decimal>> GetTotalBillingAmountPerDateRange(Nullable<System.DateTime> dFrDate, Nullable<System.DateTime> dToDate)
        {
            var dFrDateParameter = dFrDate.HasValue ?
                new ObjectParameter("dFrDate", dFrDate) :
                new ObjectParameter("dFrDate", typeof(System.DateTime));
    
            var dToDateParameter = dToDate.HasValue ?
                new ObjectParameter("dToDate", dToDate) :
                new ObjectParameter("dToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetTotalBillingAmountPerDateRange", dFrDateParameter, dToDateParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> GetTotalCollectionAmountPerDateRange(Nullable<System.DateTime> dFrDate, Nullable<System.DateTime> dToDate)
        {
            var dFrDateParameter = dFrDate.HasValue ?
                new ObjectParameter("dFrDate", dFrDate) :
                new ObjectParameter("dFrDate", typeof(System.DateTime));
    
            var dToDateParameter = dToDate.HasValue ?
                new ObjectParameter("dToDate", dToDate) :
                new ObjectParameter("dToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetTotalCollectionAmountPerDateRange", dFrDateParameter, dToDateParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> GetTotalOtherBillingAmountPerDateRange(Nullable<System.DateTime> dFrDate, Nullable<System.DateTime> dToDate)
        {
            var dFrDateParameter = dFrDate.HasValue ?
                new ObjectParameter("dFrDate", dFrDate) :
                new ObjectParameter("dFrDate", typeof(System.DateTime));
    
            var dToDateParameter = dToDate.HasValue ?
                new ObjectParameter("dToDate", dToDate) :
                new ObjectParameter("dToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetTotalOtherBillingAmountPerDateRange", dFrDateParameter, dToDateParameter);
        }
    
        public virtual ObjectResult<view_payment_center_Result> view_payment_center()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<view_payment_center_Result>("view_payment_center");
        }
    }
}
