//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payment_posting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_center
    {
        public int pc_id { get; set; }
        public string payment_center1 { get; set; }
        public string data_path { get; set; }
        public string archive_path { get; set; }
        public Nullable<int> nActive { get; set; }
        public Nullable<int> nSpecial { get; set; }
        public string specialStringForDate { get; set; }
    }
}
